language: php
php:
  #- "7.0"
  #- "5.6"
  #- "5.5"
  - "5.4"
  #- "5.3"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
before_install:
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
  - echo "extension = sqlite2.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install: # sh travis.sh
  - cd lib/plugins
  - cp -v ../../travis.sh .
  - ( cd include    && cp ../travis.sh . && sh travis.sh )
  - ( cd sqlite     && cp ../travis.sh . && sh travis.sh )
  - ( cd data       && cp ../travis.sh . && sh travis.sh )
script:
  - ( cd include/_test    && phpunit --verbose --stderr --group plugin_include )
  - ( cd sqlite/_test     && phpunit --verbose --stderr --group plugin_sqlite )
  - ( cd data/_test       && phpunit --verbose --stderr --group plugin_data )
