language: php
php:
  #- "7.0"
  #- "5.6"
  #- "5.5"
  - "5.4"
  #- "5.3"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install: # sh travis.sh
  - cp -v travis.sh lib/plugins/
script:
  - cd lib/plugins
  - ( cd include    && sh ../../travis.sh && phpunit --stderr --verbose --group plugin_include )
  - ( cd sqlite     && sh ../../travis.sh && phpunit --stderr --verbose --group plugin_sqlite )
  - ( cd data       && sh ../../travis.sh && phpunit --stderr --verbose --group plugin_data )
