language: php
php:
  #- "7.0"
  #- "5.6"
  #- "5.5"
  - "5.4"
  #- "5.3"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install: sh travis.sh
script:
  - cd lib/plugins
  - ( cd include/_test && phpunit --stderr --group plugin_include )
  - ( cd sqlite/_test && phpunit --stderr --group plugin_sqlite )
  - ( cd data/_test && phpunit --stderr --group plugin_data )
